In [1]:
import numpy as np # linear algebra
import pandas as pd

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [3]:
df = pd.read_csv("D:\\Data science\\Final project\\bank churn\\Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [5]:
X[:,2] = le.fit_transform(X[:, 2])

In [6]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)


In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [10]:
import tensorflow
tensorflow.__version__

'2.6.0'

In [11]:
# Initializing the ANN
ann = tensorflow.keras.Sequential()

In [12]:
 #Adding first input layer and the first hidden layer
ann.add(tensorflow.keras.layers.Dense(units = 6, activation = 'relu'))

In [13]:
# Adding second hidden layer
ann.add(tensorflow.keras.layers.Dense(units = 6, activation = 'relu'))

In [14]:
# Adding the output layer
ann.add(tensorflow.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [15]:
# Training the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [16]:
ann.fit(X_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 10s 4ms/step - loss: 0.5334 - accuracy: 0.7972
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4622 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4393 - accuracy: 0.7972
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4316 - accuracy: 0.7972: 0s - loss: 0.4303 - accuracy
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4268 - accuracy: 0.7972
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4235 - accuracy: 0.7972
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4205 - accuracy: 0.8011
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4180 - accuracy: 0.8204
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4153 - accuracy: 0.8248
Epoch 10/100
250/250 [==============================] - 1s 2

In [17]:
y_pred = ann.predict(X_test)

In [18]:
y_pred

array([[0.04982057],
       [0.10538682],
       [0.11966041],
       ...,
       [0.02027068],
       [0.0165998 ],
       [0.5641285 ]], dtype=float32)

In [19]:
y_pred = np.array([1 if i >= 0.5 else 0 for i in y_pred])

In [20]:
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1523   62]
 [ 216  199]]


In [22]:
from sklearn.metrics import accuracy_score
print("Accuracy Score is - {}".format(accuracy_score(y_test, y_pred)))

Accuracy Score is - 0.861


In [23]:
Unknown_data = [600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000 ]

In [24]:
Unknown_data[2] = le.transform([Unknown_data[2]])[0]

In [25]:
Unknown_data

[600, 'France', 1, 40, 3, 60000, 2, 1, 1, 50000]

In [26]:
Unknown_data = ct.transform([Unknown_data])

In [27]:
ann.predict(sc.transform(Unknown_data)) > 0.5

array([[False]])

In [32]:
Unknown_data = [376 ,'Germany','Female', 29 , 4 , 115046 , 4 , 4 , 0 , 119346]

In [33]:
Unknown_data[2] = le.transform([Unknown_data[2]])[0]

In [34]:
Unknown_data

[376, 'Germany', 0, 29, 4, 115046, 4, 4, 0, 119346]

In [35]:
Unknown_data = ct.transform([Unknown_data])

In [36]:
ann.predict(sc.transform(Unknown_data)) > 0.5

array([[ True]])